---
- name: Inlcude tasks to check operating system
  include_tasks: check_os.yml

- name: Include vars
  ansible.builtin.include_vars:
    file: "RedHat-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Install required gpg for epel repository installation
  ansible.builtin.rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  when:
    - remi_php74_install_epel_repository|bool

- name: Install required gpg for remi repository installation
  ansible.builtin.rpm_key:
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
    state: present
  when:
    - remi_php74_install_remi_repository|bool

- name: Install EPEL repository
  ansible.builtin.package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when:
    - remi_php74_install_epel_repository|bool

- name: Install REMI repository
  ansible.builtin.package:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present
  when:
    - remi_php74_install_remi_repository|bool

- name: Install PHP74 from REMI repository
  ansible.builtin.package:
    name: "{{ remi_php74_packages }}"
    state: present

- name: Add php-fpm package to extra packages
  set_fact:
    remi_php74_extra_packages: "{{ remi_php74_extra_packages + ['php74-php-fpm'] }}"
  when:
    - remi_php74_fpm_enable|bool

- name: Install extra packages
  ansible.builtin.package:
    name: "{{ remi_php74_extra_packages }}"
    state: present

- name: Inlcude task to remove unmanaged pool configurations
  include_tasks: remove-unmanaged-pool-configurations.yml

- name: Inlcude task to set php-fpm settings
  include_tasks: set-php-fpm-settings.yml
  loop: "{{ remi_php74_fpm_pools }}"
  loop_control:
    loop_var: remi_php74_fpm_pool
  when:
    - remi_php74_fpm_enable|bool
    - remi_php74_fpm_pools is defined

- name: Enable and start php-fpm service
  service:
    name: php74-php-fpm
    state: started
    enabled: true
  when:
    - remi_php74_fpm_enable|bool
    - remi_php74_fpm_pools is defined
