---
- name: Include vars
  ansible.builtin.include_vars:
    file: RedHat.yml

- name: Install required gpg for epel repository installation
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    state: present

- name: Install required gpg for remi repository installation
  ansible.builtin.rpm_key:
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
    state: present

- name: Install EPEL and REMI repository
  ansible.builtin.dnf:
    name:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
      - "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    state: present

- name: Install PHP74 from REMI repository
  ansible.builtin.dnf:
    name: "{{ remi_php74_packages }}"
    state: present

- name: Inlcude task to remove unmanaged pool configurations
  include_tasks: remove-unmanaged-pool-configurations.yml

- name: Inlcude task to set php-fpm settings
  include_tasks: set-php-fpm-settings.yml
  loop: "{{ remi_php74_fpm_pools }}"
  loop_control:
    loop_var: remi_php74_fpm_pool
  when:
    - remi_php74_fpm_enable|bool
    - remi_php74_fpm_pools is defined

- name: Enable and start php-fpm service
  service:
    name: php74-php-fpm
    state: started
    enabled: yes
  when:
    - remi_php74_fpm_enable|bool
    - remi_php74_fpm_pools is defined
